In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr.ndim

1

In [5]:
arr.size

11

In [8]:
len(arr)

11

In [6]:
arr.dtype

dtype('int32')

In [7]:
#bakılacak
arr.itemsize #byte karşılığı, 32 bit

4

In [13]:
d_1 = np.arange(20)

In [15]:
d_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
d_2 = d_1.reshape(4,5)

In [16]:
d_2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
d_3 = d_1.reshape(2,2,5)

In [18]:
d_3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [19]:
arr_sqrt = np.sqrt(arr)
arr_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [20]:
#bakılacak
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [21]:
a = np.random.randn(10)

In [22]:
a

array([ 0.56095847,  0.35446086, -0.19490713,  1.96872034,  0.63291901,
       -1.0971726 ,  0.7865651 ,  0.3232848 ,  2.15154043,  0.52745967])

In [23]:
b = np.random.randn(10)
b

array([-0.38339734,  0.00586534, -0.28356217, -0.42159453, -0.05783847,
        0.38885736,  0.67552931,  0.67713635,  1.50550422,  0.36645811])

In [25]:
np.add(a,b)

array([ 0.17756113,  0.3603262 , -0.4784693 ,  1.54712581,  0.57508054,
       -0.70831525,  1.46209441,  1.00042115,  3.65704465,  0.89391778])

In [26]:
a+b

array([ 0.17756113,  0.3603262 , -0.4784693 ,  1.54712581,  0.57508054,
       -0.70831525,  1.46209441,  1.00042115,  3.65704465,  0.89391778])

In [28]:
maxi_a = np.max(a)
maxi_a

2.1515404329373307

In [30]:
a.argmax()

8

In [31]:
np.maximum(a,b)

array([ 0.56095847,  0.35446086, -0.19490713,  1.96872034,  0.63291901,
        0.38885736,  0.7865651 ,  0.67713635,  2.15154043,  0.52745967])

In [32]:
np.maximum(a,b).sum()

7.853710453642231

In [33]:
a.max()

2.1515404329373307

In [34]:
a.min()

-1.0971726044291552

In [35]:
a.mean()

0.6013828946249532

In [36]:
a/0

C:\Users\ASUS\AppData\Local\Temp/ipykernel_16772/4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([ inf,  inf, -inf,  inf,  inf, -inf,  inf,  inf,  inf,  inf])

In [37]:
sinus = np.sin(a)
sinus

array([ 0.53199802,  0.34708479, -0.19367543,  0.92186744,  0.59150088,
       -0.8899213 ,  0.70793145,  0.31768291,  0.83605463,  0.5033399 ])

In [38]:
matrix_a = np.arange(20).reshape(4,5)
matrix_b = np.arange(10).reshape(2,5)

In [39]:
matrix_a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
matrix_b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
matrix_c = np.vstack((matrix_a, matrix_b))
matrix_c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [44]:
#The same result with above
np.concatenate([matrix_a,matrix_b])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [43]:
matrix_d = np.arange(20).reshape(5,4)
matrix_e = np.arange(10).reshape(5,2)
matrix_f = np.hstack((matrix_e,matrix_d))
matrix_f

array([[ 0,  1,  0,  1,  2,  3],
       [ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  8,  9, 10, 11],
       [ 6,  7, 12, 13, 14, 15],
       [ 8,  9, 16, 17, 18, 19]])

In [53]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8,9])


In [56]:
#coloumns of x and y  are not same. (Error)
z = np.vstack((x,y))
z

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [58]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr1 = np.array([2,5,9,4,7,6])

In [62]:
arr1.sort()
arr1

array([2, 4, 5, 6, 7, 9])

In [64]:
sorted(arr1)

[2, 4, 5, 6, 7, 9]

In [65]:
z = np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
z.shape = (2,5)


In [68]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
np.shape(z)

(2, 5)

In [70]:
z.shape

(2, 5)

In [72]:
z = z.reshape(-1)

In [74]:
even = z % 2 == 0
even

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [75]:
z[even]

array([0, 2, 4, 6, 8])

In [76]:
cond1 = z > 5
cond1

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [77]:
z[cond1]

array([6, 7, 8, 9])

In [78]:
z[z>5]

array([6, 7, 8, 9])

In [79]:
a = np.array([1,2,3,4])
b = np.array([100,200,300,400])
condition = np.array([True, True, False, False])

In [84]:
answer = [a_val if cond else b_val for a_val, b_val, cond in zip(a,b,condition)]
answer

[1, 2, 300, 400]

In [82]:
answer2 = np.where(condition, a,b)
answer2

array([  1,   2, 300, 400])

In [87]:
nums = np.arange(10)
np.where(nums<5, nums*2, nums*10)

array([ 0,  2,  4,  6,  8, 50, 60, 70, 80, 90])

In [90]:
arr = np.array([11,15,12,13,14,15,16,17,18,15,19])

In [91]:
result = np.where(arr==15)
result

(array([1, 5, 9], dtype=int64),)

In [92]:
arr = np.random.randn(5,5)

In [93]:
arr

array([[ 0.62121387,  0.98808119,  2.39326282,  0.42492819, -1.42805669],
       [ 0.65272466, -0.12526957,  0.64114046,  0.00503167,  0.18335483],
       [-0.9222703 , -0.15833731, -0.92895481, -0.59768605, -0.49312625],
       [-0.75684927, -0.50462192,  0.18384327, -0.09705352, -0.87670142],
       [ 0.14712893, -1.28659562,  0.83826375, -0.11399884,  0.28775974]])

In [95]:
np.where(arr<0, 0, arr)

array([[0.62121387, 0.98808119, 2.39326282, 0.42492819, 0.        ],
       [0.65272466, 0.        , 0.64114046, 0.00503167, 0.18335483],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.18384327, 0.        , 0.        ],
       [0.14712893, 0.        , 0.83826375, 0.        , 0.28775974]])

In [101]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [102]:
np.save("my_array", arr)

In [103]:
np.load("my_array.npy")

array([0, 1, 2, 3, 4])

In [110]:
arr1 = np.arange(10)
arr2 = np.arange(20)


In [111]:
np.savez("zip_array", x=arr1, y=arr2)

In [113]:
archive = np.load("zip_array.npz")
archive

In [114]:
archive["x"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
archive["y"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [116]:
archive.files

['x', 'y']

In [120]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
np.savetxt("mytextarray.txt",arr)

In [124]:
np.loadtxt("mytextarray.txt")

array([[1., 2., 3.],
       [4., 5., 6.]])